#!/bin/bash

set -e

# Install native dependencies for Fedora, Rocky Linux and Alma Linux (all use a Fedora image for builds)
if [ "$1" = "fedora" ] || [ "$1" = "rocky" ] || [ "$1" = "alma" ]; then
    sudo dnf group install -y "Development Tools"
    sudo dnf install -y fedora-packager rpmdevtools perl ccache rpm-sign
    sudo dnf builddep -y kernel
fi

# Configure Git
git config --global --add safe.directory '*'

# Configure PGP
echo "${PGP_KEY_PASSWORD}" | base64 -d >'/tmp/pgp-pass'
mkdir -p "${HOME}/.gnupg"
cat >"${HOME}/.gnupg/gpg.conf" <<EOT
yes
passphrase-file /tmp/pgp-pass
pinentry-mode loopback
EOT

echo "${PGP_KEY}" | base64 -d >'/tmp/private.pgp'
gpg --import /tmp/private.pgp

echo "%_signature gpg
%_gpg_name $(echo ${PGP_KEY_ID} | base64 -d)" >"${HOME}/.rpmmacros"

# Configure ccache
ccache -F 0
ccache -M 0

# Get ccache stats
ccache -s

# Get kernel source
make clone

# Patch and configure kernel
make "copy/${1}/${2}"
make "patch/${1}/${2}"
make "configure/${1}/${2}"

# Build kernel
make -l 80.0 "build/${1}/${2}"

# Package kernel
make -l 80.0 "package/${1}/${2}" PGP_KEY_ID="${PGP_KEY_ID}"

# Get ccache stats
ccache -s
