#!/bin/bash

set -e

# Configure Git
git config --global --add safe.directory '*'

# Configure PGP
echo "${PGP_KEY_PASSWORD}" | base64 -d >'/tmp/pgp-pass'
mkdir -p "${HOME}/.gnupg"
cat >"${HOME}/.gnupg/gpg.conf" <<EOT
yes
passphrase-file /tmp/pgp-pass
pinentry-mode loopback
EOT

echo "${PGP_KEY}" | base64 -d >'/tmp/private.pgp'
gpg --import /tmp/private.pgp

# Configure RPM for PGP and multithreaded compression
echo "%_signature gpg
%_gpg_name $(echo ${PGP_KEY_ID} | base64 -d)
%_binary_payload    w2T16.xzdio
%_source_payload    w2T16.xzdio" >"${HOME}/.rpmmacros"

# Configure ccache
ccache -F 0
ccache -M 0

# Get ccache stats
ccache -s

# Get kernel source
make clone BRANCH="${3}"

# Patch and configure kernel
make "copy/${1}/${2}"
make "patch/${1}/${2}"
make "configure/${1}/${2}"

# Build kernel
make -j$(nproc) "build/${1}/${2}"

# Package kernel
make -j$(nproc) "package/${1}/${2}" PGP_KEY_ID="${PGP_KEY_ID}"

# Get ccache stats
ccache -s
